package com.trustpay.vehiclehiresystem.repository;

import com.trustpay.vehiclehiresystem.model.Vehicle;
import org.springframework.util.Assert;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;

public class VehicleRepository {

    List<Vehicle> vehicleList = Collections.synchronizedList(new ArrayList<>());
    Random random = new Random();

    public Long save(Vehicle vehicle) {

        Assert.isNull(vehicle.getId(), "Id is to be generated by the add method.");

        synchronized (vehicleList) {

            vehicle.setId(random.nextLong());
            vehicleList.add(vehicle);
        }

        return vehicle.getId();
    }

    public List<Vehicle> findAll() {

        return new ArrayList<>(vehicleList);
    }

    public List<Vehicle> findByBookedTrue() {

        return vehicleList.stream().filter(v -> v.getBooked().equals(true)).collect(Collectors.toList());
    }

    public List<Vehicle> findByBookedFalse() {

        return vehicleList.stream().filter(v -> v.getBooked().equals(false)).collect(Collectors.toList());
    }
}